# Shell variables
# Generated by 'wal'
wallpaper='/home/fb/imagenes/wp3616957-blue-aesthetic-wallpapers.jpg'

# Special
background='#0a0f18'
foreground='#c6bece'
cursor='#c6bece'

# Colors
color0='#0a0f18'
color1='#29478C'
color2='#2D4B8D'
color3='#365DA7'
color4='#59659B'
color5='#8D78A4'
color6='#7089BE'
color7='#c6bece'
color8='#8a8590'
color9='#29478C'
color10='#2D4B8D'
color11='#365DA7'
color12='#59659B'
color13='#8D78A4'
color14='#7089BE'
color15='#c6bece'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
