--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/fb/imagenes/wp3616957-blue-aesthetic-wallpapers.jpg"

-- Special
background="#0a0f18"
foreground="#c6bece"
cursor="#c6bece"

-- Colors
color0="#0a0f18"
color1="#29478C"
color2="#2D4B8D"
color3="#365DA7"
color4="#59659B"
color5="#8D78A4"
color6="#7089BE"
color7="#c6bece"
color8="#8a8590"
color9="#29478C"
color10="#2D4B8D"
color11="#365DA7"
color12="#59659B"
color13="#8D78A4"
color14="#7089BE"
color15="#c6bece"
