# Shell variables
# Generated by 'wal'
wallpaper='/home/fb/.config/wpg/wallpapers/wallhaven-y8m8rg.jpg'

# Special
background='#021119'
foreground='#91d4c3'
cursor='#91d4c3'

# Colors
color0='#021119'
color1='#145866'
color2='#236C71'
color3='#2E897A'
color4='#45947D'
color5='#357983'
color6='#2D9F89'
color7='#91d4c3'
color8='#659488'
color9='#145866'
color10='#236C71'
color11='#2E897A'
color12='#45947D'
color13='#357983'
color14='#2D9F89'
color15='#91d4c3'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
