--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/fb/.config/wpg/wallpapers/wallhaven-y8m8rg.jpg"

-- Special
background="#021119"
foreground="#91d4c3"
cursor="#91d4c3"

-- Colors
color0="#021119"
color1="#145866"
color2="#236C71"
color3="#2E897A"
color4="#45947D"
color5="#357983"
color6="#2D9F89"
color7="#91d4c3"
color8="#659488"
color9="#145866"
color10="#236C71"
color11="#2E897A"
color12="#45947D"
color13="#357983"
color14="#2D9F89"
color15="#91d4c3"
