#! /bin/sh

#  ____ ____  ______        ____  __
# | __ ) ___||  _ \ \      / /  \/  |
# |  _ \___ \| |_) \ \ /\ / /| |\/| |
# | |_) |__) |  __/ \ V  V / | |  | |
# |____/____/|_|     \_/\_/  |_|  |_|
#

#
# Faus' bspwmrc
#

# Source wal colors
. "$HOME/.cache/wal/colors.sh"

pgrep -x sxhkd > /dev/null || sxhkd &
killall slstatus # Kill dwm status monitor (Spawned at .xprofile)

## Per monitor workspace
bspc monitor DVI-D-0 -d Q W E R
bspc monitor HDMI-A-0 -d 1 2 3 4

## Gap, border and padding configure
bspc config window_gap 10
# bspc config border_width 3
bspc config border_width 4
# bspc config top_padding 22
bspc config top_padding 18
bspc config normal_border_color "$color2"
bspc config active_border_color "$color11"
bspc config focused_border_color "$color11"
bspc config presel_feedback_color "$color11"
bspc config remove_disabled_monitors true
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config automatic_scheme longest_side
bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer false
bspc config click_to_focus true
bspc config history_aware_focus true


bash $HOME/.config/polybar/launch.sh

bspc rule -a Zathura state=tiled
bash /home/fb/.config/bspwm/bspwm_colors.sh &bash /home/fb/.config/bspwm/bspwm_colors.sh &bash /home/fb/.config/bspwm/bspwm_colors.sh &bash /home/fb/.config/bspwm/bspwm_colors.sh &bash /home/fb/.config/bspwm/bspwm_colors.sh &bash /home/fb/.config/bspwm/bspwm_colors.sh &