#! /bin/sh

#  ____ ____  ______        ____  __
# | __ ) ___||  _ \ \      / /  \/  |
# |  _ \___ \| |_) \ \ /\ / /| |\/| |
# | |_) |__) |  __/ \ V  V / | |  | |
# |____/____/|_|     \_/\_/  |_|  |_|
#

# Faus' bspwmrc

pgrep -x sxhkd > /dev/null || sxhkd &

## Autostart
#startup_lock_file=/tmp/bspwm-startup.lock
#if [ ! -f $startup_lock_file ]; then
#  echo "dummy" > $startup_lock_file
  
  ## Tools
  dunst &
  flameshot &
  copyq &
  udiskie & # Usb automounter daemon

  ## [DVI-D-0 ★ ] [HDMI-A-0]
  xrandr --output DVI-D-0 --primary --left-of HDMI-A-0

  ## Per monitor workspace
  bspc monitor DVI-D-0 -d Q W E R
  bspc monitor HDMI-A-0 -d 1 2 3 4

  ## Gap, border and padding configure
  bspc config window_gap 8
  bspc config border_width 3
  bspc config top_padding 22
  bspc config normal_border_color \#3c3836
  bspc config active_border_color \#7c6f64
  bspc config focused_border_color \#7c6f64
  bspc config presel_feedback_color \#7c6f64

  ## Disable monitor auto-sleep
  xset -dpms s off

  ## Wallpaper restore
  nitrogen --restore &

  ## Polybar
  bash $HOME/.config/polybar/launch.sh

  ## Compositor
  picom --config ~/.config/picom/picom.conf

#fi

bspc config border_width         8
bspc config window_gap           16

bspc config automatic_scheme      spiral
bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer false
bspc config click_to_focus        true
bspc config history_aware_focus   true
bspc config top_padding           48
bspc config bottom_padding        0
bspc config left_padding          0
bspc config right_padding         0

bspc desktop ^1 -l tiled
bspc desktop ^2 -l tiled
bspc desktop ^3 -l tiled
bspc desktop ^4 -l tiled
bspc desktop ^5 -l tiled
bspc desktop ^6 -l tiled
bspc desktop ^7 -l tiled
bspc desktop ^8 -l tiled

# Rules
# 
# Example:
# bspc rule -a mpv state=floating sticky=on rectangle=300x180+1060+475

bspc rule -a zathura state=tiled 
