#!/bin/sh

# Values
COLOR="${1:-34}"
OS=$(sh $HOME/.config/bfetch/osget | sed 's/ Linux//g')
WM=$GDMSESSION
WM=${WM^}
KERNEL=$(uname -sr | sed 's/Linux //g')
SHELL=$(basename "$SHELL")
SHELL=${SHELL^}

# It's highly recommend to used with Fetchutils:
# 	"A collection of small scripts to retrieve system information"
#
# URL:  https://github.com/lptstr/fetchutils


# Start
printf "\033[0;${COLOR}mos        \033[0m${OS:-os} ${KERNEL:-kernel}\033[0m
\033[0;${COLOR}mwm        \033[0m${WM:-wm}\033[0m
\033[0;${COLOR}mshell     \033[0m${SHELL:-shell}\033[0m"

# Arch Linux 5.10.3-arch1-1
# \033[1;${COLOR}mos        \033[0m${OS:-os}${KERNEL:-kernel}\033[0m

exit 0
