#!/bin/bash

## Created By Aditya Shakya

MENU="$(rofi -sep "|" -dmenu -i -p 'System' -location 3 -yoffset 32 -xoffset -10 -width 12 -hide-scrollbar -line-padding 4 -padding 20 -lines 4 -font "DroidSansMono NF 12" <<< " Reboot| Shutdown| Lock| Logout")"
            case "$MENU" in
                *Reboot) systemctl reboot ;;
                *Shutdown) systemctl -i poweroff;;
                *Lock) slock;;
                *Logout) bspc quit;;
            esac
